dtantsur/rust-openstack

examples/create-server.rs, examples/get-server.rs, src/compute/protocol.rs, src/compute/servers.rs, tests/integration-create-delete-server.rs
Adds support for assigning metadata key/value pairs in ServerCreate, as well as
exposing existing metadata on the get/list side.
Metadata keys and values are always strings.
I'd be happy to throw something in the `test_basic_server_ops` test which assigned a couple metadata pairs and verified that the assigned values are present in the resulting `Server` -- I wasn't sure where test coverage for this small change would be best.
=> support compute server metadata for create and get

Cargo.toml, src/auth/base.rs, src/auth/identity.rs, src/auth/simple.rs, src/common/protocol.rs, src/compute/base.rs, src/error.rs, src/image/base.rs, src/network/base.rs, src/session.rs
Taking this opportunity to rely less on the exact reqwest API.
BREAKING CHANGES:
* Custom `RequestBuilder` is removed in favor of `RequestBuilderExt`
extension trait on top of `reqwest::RequestBuilder`.
* `AuthMethod::request` and `Session::request` now return
`Result<RequestBuilder>` with `RequestBuilder` from `reqwest`.
* `Identity::new` and `NoAuth::new` now return the `Result` (using
`openstack::Error` as the error type).
* Changed `ServiceType::api_version_headers` to `set_api_version_headers`
to stop using `reqwest` headers type in the signature.
=> feat: update to reqwest 0.9 (some breaking changes)

src/common/mod.rs
BREAKING CHANGES:
`ResourceId` and `ListResources` are now private. They have
never been intended to be public.
=> fix(common): hide ResourceId and ListResources

src/auth/config.rs, src/auth/identity.rs, src/auth/mod.rs, src/identity/protocol.rs
BREAKING CHANGES:
`Identity` is now called `Password`, `PasswordAuth` was removed.
=> feat(auth): simplify password authentication (fixes #8)

src/auth/config.rs, src/auth/mod.rs, src/cloud.rs
Also add Cloud::from_config.
BREAKING CHANGES:
`auth::from_env` and `auth::config` now return `Result<Session>`
=> chore(auth): make from_env and from_config return Session (#9)

Cargo.toml
This might need a couple of iterations before you're happy with it, but let's see.
I'm using rust-openstack in an internal tool, and I want to be able to build it into a binary with as few dependencies as possible that can run on lots of systems. Currently that's a bit painful because it depends on the system openssl library, and isn't portable between e.g. Ubuntu and Centos systems if they have slightly different OpenSSL library versions.
https://github.com/ctz/rustls is a pure-Rust HTTPS library, so avoids the system openssl dependency, and reqwest exposes a feature to use that for HTTPS instead.
`rusoto_ec2` takes an approach of exposing `rustls` and `native-tls` features so users can explicitly choose between them. I worry that would be a bit fiddlier for rust-openstack, because to …
=> Use rustls instead of native-tls to avoid non-Rust dependencies

src/network/networks.rs
The 'shared' field is present and editable in Network, but it wasn't
in NewNetwork. It is now added to NewNetwork as well to allow creation
of shared networks.
=> Allow setting 'shared' on NewNetwork

src/network/protocol.rs
Having Eq and PartialEq on these structures helps when you want to
assert in tests that e.g. a Subnet contains a certain AllocationPool.
=> Derive Eq and PartialEq for trivial networking API protocol bits

src/compute/protocol.rs, src/compute/servers.rs
Thanks for this useful crate!
The proposed changes allow to set the availability zone for new servers.
=> Allow to set availability zone for new servers

zuul.d/jobs.yaml
Xenial seems no longer supported.
=> chore(ci): use Bionic for master/train CI jobs

src/object_storage/objects.rs
Add a method for retreiving object url, because when creating an object (in object storage) there was no way to retreive the url.
As stated in my previous pull request, I begin in rust and would appreciate any comments to improve the pull request.
=> Add url method to Object

src/cloud.rs, src/object_storage/api.rs, src/object_storage/mod.rs, src/object_storage/objects.rs, src/object_storage/protocol.rs
First I want to thank you for your lib.
I add the availibitily to send custom headers during an object creation. This allows for exemple to use 'X-Delete-After' for adding a ttl to the object.
I choose to send headers, this way there is more flexibility and everyone can use the headers he wants based on the openstack doc.
I just start developping in rust from few days, so I didn't publish tests with it (though I have tested it with a personnal project). Also feel free to give me some comments and I will be glad to improve it.
=> Object Storage: add availability to use custom headers

Cargo.toml, examples/list-containers.rs, examples/list-objects.rs, src/object_storage/objects.rs, src/object_storage/protocol.rs, tests/integration-object-storage.rs
This PR:
* add some examples about object stores: 
* list containers, 
* and list the first 10 objects of a given container;
* add hash to objects
The hash of an object [is described as the following](https://docs.openstack.org/api-ref/object-store/?expanded=get-object-content-and-metadata-detail#get-object-content-and-metadata):
> For objects smaller than 5 GB, this value is the MD5 checksum of the object content. The value is not quoted. For manifest objects, this value is the MD5 checksum of the concatenated string of ETag values for each of the segments in the manifest, and not the MD5 checksum of the content that was downloaded. Also the value is enclosed in double-quote characters. You are strongly recommended to compute the MD5 checksum of the response body as it is received and …
=> [Object store] add hash to objects

examples/get-server.rs, src/compute/api.rs, src/compute/protocol.rs, src/compute/servers.rs, tests/integration-create-delete-server.rs
BREAKING CHANGE
Changes the signature of Server.flavor()
=> feat(compute): rework the server's flavor field handling (closes #146)

.github/workflows/main.yml, Cargo.toml, src/lib.rs
We have some CI jobs failing due to the version of `regex` we have requiring Rust 1.65.
=> chore(ci): bump MSRV

src/compute/protocol.rs
When performing a detailed server query against a cloud with VMs in state `Rebuild` we get
```
Error { kind: ProtocolError, message: "error decoding response body: Unexpected ServerStatus: REBUILD at line 1 column 46882", status: None }
```
from Serde. This PR fixes the error by adding a `Rebuild` status to the `ServerStatus` enum.
=> Add 'Rebuild' to ServerStatus enum

Cargo.toml, src/network/mod.rs, src/network/ports.rs, src/network/protocol.rs
`eui48` has a dependency on the deprecated `rustc-serialize` package so convert to use `macaddr`.
Fixes #140
=> Port from eui48 to macaddr

src/compute/api.rs, src/compute/mod.rs, src/compute/servers.rs, src/utils.rs
This moves the server actions to use a typed enum to represent the possible actions that can be performed on a server.
In the future, I wouldn't expect that [every single action](https://docs.openstack.org/api-ref/compute/#servers-run-an-action-servers-action) would have a special method associated with it, so I opted for a generic `action` method which takes the new enum as an argument.
This now allows you to do:
```rust
server.action(ServerAction::Stop).await?
server.action(ServerAction::Reboot {reboot_type: Soft}).await?
```
which is equivalent to (the still-present)
```rust
server.stop().await?
server.reboot(Soft).await?
```
This is more verbose but will make it easier to implement the rest of the actions in the future as I would like to add the `createImage` action next, but I wanted …
=> Implement server actions via an enum

src/compute/servers.rs
This adds the function `ServerQuery.all_tenants` which sets the optional
`all_tenants` flag on the server list query. This is useful for admin users
wanting to retrieve all servers of an OpenStack cloud.
It furthermore adds the convenience function `DetailedServerQuery.all`.
=> List servers for all tenants

Cargo.toml, src/block_storage/api.rs, src/block_storage/mod.rs, src/block_storage/protocol.rs, src/block_storage/volumes.rs, src/cloud.rs, src/lib.rs, tests/integration-block-storage.rs, tests/integration-list-resources.rs
This starts adding the block storage API alias cinder. So far it implements rudimentary versions of `list_volumes`, `find_volumes` and `get_volume` with an equally minimal `Volume` struct. But I does compile and returns things.
Although the cinder API is very similar to nova's API, this is currently closer to the image module. For example, at the moment it goes directly to the `/volumes/detail` endpoint, rather than defining some kind of `VolumeSummary` for `/volumes` and offering a `detailed()` as the `compute` module does.
This is for simplicity, just to get things rolling. I need this at work, so I can invest a fair bit of time. I'll make it more consistent along the way.
=> Add Block Storage API

.github/workflows/functional.yaml
The user account ATiltedTree which hosted the setup-rust action just vanished
from Github. This causes the functional tests to fail. This replaces said
action with actions-rust-lang/setup-rust-toolchain.
Signed-off-by: Sandro-Alessio Gierens <sandro@gierens.de>
=> Replace Removed Setup Rust Github Action

src/block_storage/protocol.rs, src/block_storage/volumes.rs
This revises the datetime handling for Volumes to the usual chrono::DateTime.
In cases where Openstack does not return timezone information UTC is assumed.
Signed-off-by: Sandro-Alessio Gierens <sandro@gierens.de>
=> refactor(block_storage): changes back Volume datetimes to chrono::DateTime

.github/workflows/audit.yml, deny.toml
This adds the config file for cargo deny which automatically checks for things
like advisories, licenses, bans, ... and a corresponding audit workflow that
runs on every push changing dependencies and every night.
Signed-off-by: Sandro-Alessio Gierens <sandro@gierens.de>
=> Add cargo deny config and audit workflow

.github/workflows/functional.yaml
The OpenStack Zed tests are failing. Since Zed is EOL anyway this simply
removes them and instead adds the new Caracal version to the functional
workflow.
=> Update OpenStack version in Functional Tests

.github/workflows/main.yml, Cargo.toml, src/lib.rs
CI seems to be failing on rust 1.65 due to tokio requiring 1.70. Maybe
this crate should also update its minimum version to 1.70. This updates the
version in the `Cargo.toml` and the `lib.rs` docstring and the `main.yml` workflow.
=> Update minimal rust version

Cargo.toml, src/block_storage/volumes.rs, src/common/types.rs
Rust 1.80 which is used in functional tests does more extensive cfg linting.
Because `volume` and `identity` are not known it causes functional tests to fail.
This adds a linting rule to allow both those values.
For more info see: https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html#checked-cfg-names-and-values
=> Fix Rust 1.80 cfg Linting and add VolumeRef impls

examples/create-delete-volume.rs, examples/get-volume.rs, examples/list-volumes.rs
This adds a new examples:
- `list-volumes.rs`
- `get-volume.rs`
- `create-delete-volume.rs`
=> Add volume examples

src/compute/api.rs, src/compute/servers.rs
This adds most of the remaining [server actions](https://docs.openstack.org/api-ref/compute/#servers-run-an-action-servers-action).
This includes all of the simple actions which have very single or no arguments taken and return nothing, as well as some which take relatively simple arguments (e.g. a few strings) but might return values.
The first question is, given the diversity of return values given by these actions, is it ok for us to provide that as a generic `serde_json::Value`, or should we define deserialisable structs for each action that provides a value? Perhaps the generic `Server::action` should return a `serde_json::Value`, but if we implement specific functions for any other actions in the future (like we already have for e.g. `Server::stop`) we define return type …
=> Add more server actions

src/compute/api.rs, src/compute/protocol.rs, src/compute/servers.rs, tests/integration-create-delete-server.rs
Follow-up to https://github.com/dtantsur/rust-openstack/pull/149
=> Clean up server actions API
